apiVersion: v2
name: cert-mounter-example
description: cert mounter for rtd
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: cert-mounter-blueprint
  version: 1.0.0
  repository: "https://pagopa.github.io/aks-helm-cert-mounter-blueprint"
